### ISSUE TITLE
Weasel Does not work on Android 5.0+

### ISSUE THREAD

**Issue by HenryHoggard** [WithSecureLabs/drozer#191]
Ref: https://github.com/mwrlabs/drozer/issues/139

Weasel needs to be compiled with PIE for Android 5.0+

**Comment by metall0id** [comment]
Here be dragons. Part of weasel's code deals with using the Dalvik VM directly to run a JAR. This bypasses the need to have the `INSTALL_PACKAGES` permission and effectively takes over a process with drozer code.

In Android 5.0 and above the runtime has been replaced with ART. This means that this will be a little more work than a new compilation.
