### ISSUE TITLE
how can they improt valuescan file in drozer

### ISSUE THREAD

**Issue by ykxxxbc** [WithSecureLabs/drozer#351]
hi 
I am studying how to use drozer ，and i find a interesting post 
Poster say just import the xml file to drozer just run 
I don't know how can they do this 
like the picture show 
![image](https://user-images.githubusercontent.com/38181319/61817243-afcceb00-ae80-11e9-8f82-6f86dd9ed871.png)
I am not good at english,hope you can understand what i am talking about
Many thanks for help !

**Comment by Yogehi** [comment]
can you provide poster link?
