### ISSUE TITLE
Drozer does not enumerate custom urls schemes for some apps

### ISSUE THREAD

**Issue by hackOtack** [WithSecureLabs/drozer#364]
### Steps to reproduce
App com.geico.mobile has these two browsable urls 

     `  <activity android:name=".android.ace.geicoAppPresentation.geniusLinks.AceGeniusLinkLandingActivity" launchMode="singleTask" noHistory="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.BROWSABLE" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:scheme="com.geico.genius" />
            </intent-filter>
            <intent-filter>
                <data android:scheme="geicoappdeeplink" />
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>
        </activity>`

### Expected behaviour
should print these two custom url schemes. 

### Actual behaviour
no result:

![drozer](https://user-images.githubusercontent.com/6277368/68686107-1ca3e800-0539-11ea-8530-fb5ab1dbc70b.png)

### Environment

drozer version -->  (v2.4.4)

**Comment by hackOtack** [comment]
link to the app: https://play.google.com/store/apps/details?id=com.geico.mobile&hl=en_CA

**Comment by rhishinathvarma** [comment]
for me also the custom browsable urls and schemes are not working for some apps

**Comment by Yogehi** [comment]
What package names are you running it against?

**Comment by rhishinathvarma** [comment]
I run scan over multiple applications but now working

**Comment by rhishinathvarma** [comment]
Is there anything to add in the package? to run those scans?
