### ISSUE TITLE
Drozer not running in catelina OS 

### ISSUE THREAD

**Issue by d3tonator** [WithSecureLabs/drozer#367]
I tried to install drozer using below-mentioned URL but it's not installing properly. 
https://blog.ropnop.com/installing-drozer-on-os-x-el-capitan/

I have got lot's of dependency error 
Then I follow the method from Drozen Documentation Guide still it's not working in my  Mac. Can any help to resolve the issue.

**Comment by sandeephodkasia** [comment]
Facing same problem . 

```(drozer) (base) apples-MacBook-Pro:pyOpenSSL-0.13 apple$ python2.7 setup.py build_ext -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
running build_ext
building 'OpenSSL.crypto' extension
creating build/temp.macosx-10.15-x86_64-2.7
creating build/temp.macosx-10.15-x86_64-2.7/OpenSSL
creating build/temp.macosx-10.15-x86_64-2.7/OpenSSL/crypto
cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -iwithsysroot /usr/local/libressl/include -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -pipe -I/usr/local/opt/openssl/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c OpenSSL/crypto/crypto.c -o build/temp.macosx-10.15-x86_64-2.7/OpenSSL/crypto/crypto.o
OpenSSL/crypto/crypto.c:57:14: warning: implicit conversion loses integer
      precision: 'Py_ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
    nchars = PyBytes_Size(ret);
           ~ ^~~~~~~~~~~~~~~~~
OpenSSL/crypto/../py3k.h:34:22: note: expanded from macro 'PyBytes_Size'
#define PyBytes_Size PyString_Size
                     ^
OpenSSL/crypto/crypto.c:235:15: warning: implicit conversion loses integer
      precision: 'long' to 'int' [-Wshorten-64-to-32]
    buf_len = BIO_get_mem_data(bio, &temp);
            ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/opt/openssl/include/openssl/bio.h:462:34: note: expanded from macro
      'BIO_get_mem_data'
# define BIO_get_mem_data(b,pp)  BIO_ctrl(b,BIO_CTRL_INFO,0,(char *)(pp))
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
OpenSSL/crypto/crypto.c:338:15: warning: implicit conversion loses integer
      precision: 'long' to 'int' [-Wshorten-64-to-32]
    buf_len = BIO_get_mem_data(bio, &temp);
            ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/opt/openssl/include/openssl/bio.h:462:34: note: expanded from macro
      'BIO_get_mem_data'
# define BIO_get_mem_data(b,pp)  BIO_ctrl(b,BIO_CTRL_INFO,0,(char *)(pp))
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
OpenSSL/crypto/crypto.c:441:15: warning: implicit conversion loses integer
      precision: 'long' to 'int' [-Wshorten-64-to-32]
    buf_len = BIO_get_mem_data(bio, &temp);
            ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/opt/openssl/include/openssl/bio.h:462:34: note: expanded from macro
      'BIO_get_mem_data'
# define BIO_get_mem_data(b,pp)  BIO_ctrl(b,BIO_CTRL_INFO,0,(char *)(pp))
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
OpenSSL/crypto/crypto.c:626:16: error: variable has incomplete type 'EVP_MD_CTX'
      (aka 'struct evp_md_ctx_st')
    EVP_MD_CTX md_ctx;
               ^
/usr/local/opt/openssl/include/openssl/ossl_typ.h:92:16: note: forward
      declaration of 'struct evp_md_ctx_st'
typedef struct evp_md_ctx_st EVP_MD_CTX;
               ^
OpenSSL/crypto/crypto.c:673:16: error: variable has incomplete type 'EVP_MD_CTX'
      (aka 'struct evp_md_ctx_st')
    EVP_MD_CTX md_ctx;
               ^
/usr/local/opt/openssl/include/openssl/ossl_typ.h:92:16: note: forward
      declaration of 'struct evp_md_ctx_st'
typedef struct evp_md_ctx_st EVP_MD_CTX;
               ^
4 warnings and 2 errors generated.
```

**Comment by Josue198s** [comment]
I got the same problem, and python 2 is not supported anymore. I don't know if they will release a drozer with python3.

**Comment by fujiokayu** [comment]
I installed drozer on macOS Catalina and wrote how.
https://github.com/fujiokayu/Installing-Drozer-on-macOS-Catalina

Tell me if you can't install this way.

**Comment by chevonmdphillip** [comment]
I have found a workaround and will be doing documentation on it in my blog post. It took my hours for google searching and trying different things. I finally got it to work.

**Comment by jdonsec** [comment]
> I installed drozer on macOS Catalina and wrote how.
> https://github.com/fujiokayu/Installing-Drozer-on-macOS-Catalina
> 
> Tell me if you can't install this way.

Thank you so much for the Catalina OS documentation. 
It worked for me, I did have to install Java JDK and twisted package.

Not a fan that I need to run pipenv shell all the time, but I am glad this worked after hours of trying it out.

**Comment by Josue198s** [comment]
> I have found a workaround and will be doing documentation on it in my blog post. It took my hours for google searching and trying different things. I finally got it to work.

Can you share the work around?

Regards

**Comment by Yogehi** [comment]
i'm interested in the workaround as well, but we now have a docker image that should help too

https://github.com/FSecureLABS/drozer/tree/develop/docker

**Comment by ponkape** [comment]
FYI. Got Drozer running locally with Sonoma 14.0 version. As installing prerequisite packages with Python venv and installing Java JDK using OnePlus physical phone. Also, did this trick mentioned in this [comment](https://github.com/WithSecureLabs/drozer/issues/361#issuecomment-667578866), so all the Drozer functionalities would work.

**Comment by cyberMilosz** [comment]
Hi there, sorry for the delayed response!

As others have commented, drozer has some very specific (and dated) software pre-requisites, namely Python 2.7 and Java 7. We hope to resolve these issues in a future version, but we can't comment on when exactly that will happen.

In the meantime, the easier way to run drozer is through our official Docker container: https://hub.docker.com/r/withsecurelabs/drozer
