### ISSUE TITLE
How do I solve this problem 【Unexpected [Errno 2] No such file or directory】

### ISSUE THREAD

**Issue by coffeehb** [WithSecureLabs/drozer#379]
Hi, everyone. I see many friends have this problem. I also encountered this problem in the process of using, which puzzled me for 2 days. At last, I used this method to solve it. The system is helpful to you.

Error messages are not fixed. There are examples.
![image](https://user-images.githubusercontent.com/5829776/84613924-1de62a80-aef7-11ea-8ff6-4261ac203026.png)

![image](https://user-images.githubusercontent.com/5829776/84613948-2b9bb000-aef7-11ea-9359-c20a7d03ee10.png)

![image](https://user-images.githubusercontent.com/5829776/84613958-33f3eb00-aef7-11ea-9865-8b7ac4b6f890.png)

After my research, I have a file with empty content / users / ***** /. Drozer_ history, When I delete it, I reconnect and it works

rm ~/.drozer_history
and, restart drozer.
drozer console connect

![image](https://user-images.githubusercontent.com/5829776/84614074-94832800-aef7-11ea-8f2d-7c8044ad4332.png)

**Comment by F1sh1001** [comment]
thank you!!!!!!!!!!!!!!

**Comment by paradiseduo** [comment]
very good!!

**Comment by Yogehi** [comment]
pinned issue for now until i know what to do with this.
