### ISSUE TITLE
ERROR: drozer-2.x.x-py2-none-any.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by mwanza-k** [WithSecureLabs/drozer#393]
When i try install drozer wheel i get the ERROR: drozer-2.x.x-py2-none-any.whl is not a supported wheel on this platform.

O.s version kali linux release 2020.1

**Comment by Yogehi** [comment]
![image](https://user-images.githubusercontent.com/10925671/222906228-ef367c2a-df1e-44c3-ae61-f4ff86396557.png)
