### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by 0x676f64** [WithSecureLabs/drozer#396]
It's been a while since I've used Drozer via Windows 10. 

I updated to the 2.4.4 version, started the app, forwarded the correct port, but continue to get this error message 

![DRZ](https://user-images.githubusercontent.com/29809506/131204498-21895ed3-92ba-48e6-aef7-a775a257c90a.PNG)

I tried uninstalling dependencies and re-installing them, but with the EOL of Python2.7, it's been growing more and more frustrating. 
Any help on this would be very appreciated.

**Comment by Yogehi** [comment]
try the docker image please

https://github.com/FSecureLABS/drozer/tree/develop/docker
