### ISSUE TITLE
my own module can't proceed from beginning

### ISSUE THREAD

**Issue by boapgt** [WithSecureLabs/drozer#398]
here is my module code:
################################################################################
from drozer.modules import Module

class GetInteger(Module) :
	name = "Get Device info"
	description = "A module that returns information about the device and hardware features"
	examples = "run ex.device.getinteger"
	date = "10-11-13"
	author = "Keith Makan"
	license = "BSD (3-clause)"
	path = ["ex","device"]
def execute (self,arguments) :
	build = self.new ("android.os.Build")
	self.stdout.write ("Getting device info . . . \n")
	self.stdout.write ("[ * ] BOARD : %s\n" % (build.BOARD) )
	self.stdout.write ("[ * ] BOOTLOADER : %s\n" % (build.BOOTLOADER) )
	self.stdout.write ("[ * ] BRAND : %s\n" % (build.BRAND) )
	self.stdout.write ("[ * ] CPU__ABI : %s\n" % (build.CPU__ABI) )
	self.stdout.write ("[ * ] CPU__ABI2 : %s\n" % (build.CPU__ABI2) )
	self.stdout.write ("[ * ] DEVICE : %s\n" % (build.DEVICE) )
	self.stdout.write ("[ * ] DISPLAY : %s\n" % (build.DISPLAY) )
	self.stdout.write ("[ * ] FINGERPRINT : %s\n" % (build.FINGERPRINT) )
	self.stdout.write ("[ * ] HARDWARE : %s\n" % (build.HARDWARE) )
	self.stdout.write ("[ * ] MANUFACTURER : %s\n" % (build.MANUFACTURER) )
	self.stdout.write ("[ * ] MODEL : %s\n "% (build.MODEL) )
	self.stdout.write ("[ * ] TAGS : %s\n" % (build.TAGS) )

###########################################################################
but when i run it ,
"does not define an execute() method" is showed
but i really define the execute.
so where is  wrong??
![image](https://user-images.githubusercontent.com/51245222/145910326-2321bec6-3ad4-452f-8cc8-203b6465a8c0.png)

**Comment by cyberMilosz** [comment]
We're sunsetting all issues related to drozer 2. If your issue persists in drozer 3, please open a new issue!
