### ISSUE TITLE
syntex error pleased solve it same problem have many people

### ISSUE THREAD

**Issue by kaal-kali** [WithSecureLabs/drozer#400]
drozer console connect                                                                                   Traceback (most recent call last):                                                                                        File "C:\Python27\Scripts\drozer", line 30, in <module>                                                                   __import__("drozer.cli.%s" % (sys.argv[1]))                                                                           File "C:\Python27\lib\site-packages\drozer\cli\console.py", line 8, in <module>                                           from drozer.console import Console                                                                                    File "C:\Python27\lib\site-packages\drozer\console\__init__.py", line 4, in <module>                                      from drozer.console.console import Console                                                                            File "C:\Python27\lib\site-packages\drozer\console\console.py", line 5, in <module>                                       from pydiesel.api.protobuf_pb2 import Message                                                                         File "C:\Python27\lib\site-packages\pydiesel\api\__init__.py", line 9, in <module>                                        from pydiesel.api.frame import Frame                                                                                  File "C:\Python27\lib\site-packages\pydiesel\api\frame.py", line 3, in <module>                                           from pydiesel.api.protobuf_pb2 import Message                                                                         File "C:\Python27\lib\site-packages\pydiesel\api\protobuf_pb2.py", line 3, in <module>                                    from google.protobuf import descriptor                                                                              ImportError: No module named google.protobuf

**Comment by reewardius** [comment]
install python 2.7 or install Appie https://manifestsecurity.com/appie/

Path to drozer will be DISK:\Appie\base\drozer.bat

**Comment by Yogehi** [comment]
![image](https://user-images.githubusercontent.com/10925671/222906101-c6f1fd81-d1c9-4eb0-952d-82574433e105.png)
