### ISSUE TITLE
WheN try to setup drozer it shows SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by joyahamad074** [WithSecureLabs/drozer#403]
### Steps to reproduce
Hi,
I have face some issue during the installation of drozer.
when I try to setup the drozer using `python.exe setup.py bdist_msi`
it shows me this kind error:
```
Traceback (most recent call last):
  File "C:\Users\User\Downloads\drozer-develop\setup.py", line 8, in <module>
    from src.drozer import meta
  File "C:\Users\User\Downloads\drozer-develop\src\drozer\meta.py", line 63
    print "%s %s\n" % (name, version)
          ^
SyntaxError: invalid syntax

```

And That's why I cannot install it. Please can anyone help me to how get rid out of it??

**Comment by Yogehi** [comment]
![image](https://user-images.githubusercontent.com/10925671/222906088-fd8e349c-023a-43e3-b956-ce171103b11e.png)
