### ISSUE TITLE
startActivityForResult() Module

### ISSUE THREAD

**Issue by ghost** [WithSecureLabs/drozer#57]
A fairly common Android pattern is to start an `Activity` that will return some information as it `finish()`es.

It would be nice to have a module that performs this interaction with an exported activity, `app.activity.startforresult` alongside `app.activity.start`. This would intercept the reply and make the Intent available for inspection.

**Comment by joaonlima** [comment]
Hey there, I've started to put something together to do this one.. 
I've added an activity to drozer-agent, this activity receives a start intent with another intent as extra (this will be used to startForResult the target activity). 
Currently the result of the ```onActivityResult()``` is just added to a file and read by the drozer console, but of course this is not ideal. 
Do you guys have any suggestions? (I started trying to use just a static variable to hold this value, but the console and the agent get different classes/loaders and so it does not work)
